# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=10, unique=True)),
                ('Nombre', models.CharField(max_length=10)),
                ('Fecha_inicio', models.DateField(null=True)),
                ('Fecha_Fin', models.DateField(null=True)),
                ('Encargado', models.CharField(max_length=10, null=True)),
                ('Descripcion', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
