# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Rol',
        ),
    ]
