# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=30)),
                ('ApellidoMaterno', models.CharField(max_length=30)),
                ('Nombres', models.CharField(max_length=30)),
                ('Titulo', models.CharField(choices=[('Sr.', 'Señor'), ('Sra.', 'Señora'), ('Ing.', 'Ingeniero(a)'), ('Lic.', 'Licenciado(a)'), ('Arq.', 'Arquitecto(a)'), ('Dr.', 'Doctor'), ('Dra.', 'Doctora'), ('Mtr.', 'Master')], default='Sr.', max_length=5)),
                ('CI', models.CharField(max_length=10)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Organizador', models.CharField(max_length=30)),
                ('Lugar', models.CharField(max_length=60)),
                ('Fecha', models.DateField()),
                ('Expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminarios.Expositor')),
            ],
        ),
    ]
